### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-lauraferrandof#1]
Really good job @lauraferrandof  !!!

Here you have some tips to improve the exercise:

- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Define the logic to make the counter work
- [x] On callback function you can store on a constant the parsed number and reuse it on if/else. This way you avoid writing `parseInt()` so many times.
- [ ] Extract the feedback painter to a function
- [x] Fix the if's structure: check for the winner option, then the other and then for the rest is enough with an `else` statement

Let me know if you have any doubts ;)

Go for it!!

**Comment by lauraferrandof** [comment]
Hi @nasivuela ! Thank you for your feedback :)

I think I fixed everything you told me. I still have 2 main doubts concerning my JS code though:

1. Are the `console.log`s where they're supposed to be?
2. Are the variables declared where they're supposed to be? I mean the ones I declared within the functions. I never know if I should declare a variable inside or out.

I also added the Adalab Starter Kit, fixed some things in the HTML file, did the styles, created a READMe and published the page in GitHub Pages.

Let me know if there's something I can improve, especially in the JS code!!

**Comment by nasivuela** [comment]
Well done @lauraferrandof !!

I'm closing this, but here you have more tips in case you want to keep improving it:
- Your logs and variables declarations are ok!
- Extract the feedback painter to a function -> you are writing many times `tipBoxEl.innerHTML = '¡HAS GANADO, CAMPEONA!';` so you can extract it to a function to reuse it.
- You can check other cases: the user does not write anything, the user writes something bigger than 100...
- What about adding a reset feature?
- ... whatever else you want to practice!

![](https://media.giphy.com/media/dkGhBWE3SyzXW/giphy.gif)
